language: node_js
node_js:
  - "6.5.0"
services:
  - redis-server
script:
  - npm run coverage
before_install:
  - pip install --user codecov
  - $CXX --version
after_success:
  - codecov --file coverage/lcov.info --disable search
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
